/*
 * Copyright 2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import configurationCache.ConfigurationCacheReportPage
import configurationCache.reportPageModelFromJsModel
import elmish.elementById
import elmish.mountComponentAt
import org.gradle.problems.internal.report.model.parseCcReportJsModel
import org.gradle.problems.internal.report.model.parseProblemsJsModel
import problemReport.ProblemsReportPage
import problemReport.problemsReportPageModelFromJsModel


fun main() {
    val jsModel = configurationCacheProblems()
    // We stringify the JS object and parse it back with kotlinx.serialization instead of decoding the
    // dynamic object directly: `decodeFromDynamic` pulls in noticeably more code and inflates the
    // report bundle. Reading `problemsReport` off the dynamic object first keeps mode detection cheap.
    // TODO(mlopatkin): change the generated format so `configurationCacheProblems()` returns the JSON
    //  string directly. Then we can decode it without materializing an intermediate JS object at all,
    //  which matters for reports that can reach several megabytes.
    val reportJson = JSON.stringify(jsModel)
    if (jsModel.problemsReport == null) {
        mountComponentAt(
            elementById("report"),
            ConfigurationCacheReportPage,
            reportPageModelFromJsModel(parseCcReportJsModel(reportJson))
        )
    } else {
        // A problems report reuses the top-level `diagnostics` array to carry its problems, because
        // producers write the diagnostics in a predefined order on the fly to the html report file.
        val problemsModel = parseProblemsJsModel(reportJson)
        mountComponentAt(
            elementById("report"),
            ProblemsReportPage,
            problemsReportPageModelFromJsModel(
                problemsModel.problemsReport,
                problemsModel.diagnostics
            )
        )
    }
}


/**
 * External model defined in `configuration-cache-report-data.js`, a file generated by
 * `ConfigurationCacheReport`.
 */
private
external val configurationCacheProblems: () -> dynamic
