[versions]
kotlin = "2.4.0"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-gradle-plugin = { module = "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
gradle-kotlin-dsl-conventions = { module = "org.gradle.kotlin:gradle-kotlin-dsl-conventions", version = "0.9.0" }
